openapi: 3.0.0
info:
  title: biergit.ch api
  version: 1.0.0
  description: API for the biergit.ch backend
  contact:
    name: biergit
    email: api@biergit.ch
servers:
  - url: 'https://biergit.ch/api/v1/'
tags:
  - name: groups
    description: groups
  - name: profiles
    description: profiles
security:
  - OAuth2: []
paths:
  /groups:
    get:
      tags:
        - groups
      summary: Get all groups
      description: |
        get all groups.
      security:
        - OAuth2: []
      responses:
        '200':
          description: Successful 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Groups'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  /groups/{groupId}:
    get:
      tags:
        - groups
      summary: update group
      security:
        - OAuth2: [read]
      description: |
        Gets group by id
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
          description: Numeric ID of the group to get        
      responses:
        '200':
          description: Successful 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Groups'
    delete:
      tags:
        - groups
      summary: delete group
      security:
        - OAuth2: [delete_group]
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
          description: Numeric ID of the group to get
      responses:
        '200':
          description: Successful 
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  /groups/{groupId}/members:
    post:
      tags:
        - groups
      summary: groups
      description: |
        Invite users to group, invitation emails are being sent out 
      security:
        - OAuth2: [write]
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
          description: Numeric ID of the group to get  
        - in: body
          name: email
          schema:
            type: array
            items:
              type: string
              format: email
          required: true
          description: One or more email(s) of the user(s) to invite        
      responses:
        '202':
          description: Successful       
    get:
      tags:
        - groups
      summary: Get all members of a groups
      description: |
        Get all members of a groups
      security:
        - OAuth2: [write]
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get        
      responses:
        '200':
          description: Successful 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
  /groups/{groupId}/verify/{verificationToken}:
    get:
      tags:
        - groups
      summary: Link to join a group
      description: |
        Join a group.
      security:
        - OAuth2: [read]
      parameters:
        - in: path
          name: groupId
          schema:
            type: integer
          required: true
          description: Numeric ID of the user to get        
        - in: path
          name: verificationToken
          schema:
            type: string
          required: true
          description: JWT generated by the backend
      responses:
        '200':
          description: Successful 
  /profiles/me:
    get:
      tags:
        - profiles
      summary: Get my profile data
      description: |
        Get my profile
      security:
        - OAuth2: [read]
      responses:
        '200':
          description: Successful 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User' 

  /expenses:
    post:
      tags:
        - expenses
      summary: expenses
      name: expense
      description: |
        Create new expense
      security:
        - OAuth2: [read]
      parameters:
        - in : body
          name: expense
          schema:
            $ref: '#/components/schemas/Expense'
      responses:
        '201':
          description: Successful       
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OpenID:
      type: openIdConnect
      openIdConnectUrl: https://biergit.eu.auth0.com/.well-known/openid-configuration
    OAuth2:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://tools.ietf.org/html/rfc6749#section-1.3.2)
      flows:
        implicit:
          authorizationUrl: https://biergit.eu.auth0.com/authorize
          scopes: {}
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    ForbiddenError:
      description: You don't have the permission to perform this action
  schemas:
    Groups:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/Group'
    Group:
      type: object
      properties:
        id:
          type: string
          example: d70eac2d-0b96-49e6-95cb-3e55574fa5bc
        name:
          type: string
          example: "Bier Gruppe"
    Users:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: string
          example: d70eac2d-0b96-49e6-95cb-3e55574fa5bc
        name:
          type: string
          example: "Frau Biergit"
        email:
          type: email
          example: "frau.biergit@biergit.ch"
    Expenses:
      type: array
      items:
        allOf: 
          - $ref: '#/components/schemas/Expense'
    Expense:
      type: object
      properties:
        context:
          type: string
          nullable: true
          example: d70eac2d-0b96-49e6-95cb-3e55574fa5bc
          description: Can be used as user or group id
        from:
          type: string
          example: d70eac2d-0b96-49e6-95cb-3e55574fa5bc
          description: Unique userid
        to: 
          type: array
          items:
            type: string
            example: d70eac2d-0b96-49e6-95cb-3e55574fa5bc
            description: userid
          description: a list of userids
        quantity:
          type: integer
          example: 3